##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
a = [1,2,3,4,5,6]
a[0]

In [5]:
arr[[0,2,4]]

array([10, 30, 50])

You can do this fancy indexing in 2D Matrix aswell

In [6]:
matrix = np.arange(1,13).reshape(3,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
matrix[[0,1],[1,2]]

array([2, 7])

##Conditional Selection
Find values based on conditions or replace them.

In [9]:

arr = np.array([5,12,18,7,30])
arr>12

array([False, False,  True, False,  True])

In [10]:
np.where(arr>12)

(array([2, 4]),)

In [11]:
np.where(arr>12,arr,0)

array([ 0,  0, 18,  0, 30])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [12]:
arr = np.array([42,5,18,23])
np.sort(arr)

array([ 5, 18, 23, 42])

In [13]:
np.argsort(arr)

array([1, 2, 3, 0])

##Concatenation & Stacking

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [17]:
B

array([[5, 6],
       [7, 8]])

In [3]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.hstack((B,A))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [5]:
np.concat([A,B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])