##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [1]:
a = [10,20,30,40]
b = [1,2,3,4]
print(a+b)

[10, 20, 30, 40, 1, 2, 3, 4]


In [2]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a-b)
print(a*b)
print(a/b)

[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [5]:
a = [1,2,3,4]
print(a*2)
a =np.array([1,2,3,4])
print(a*2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [6]:
arr = np.array([4,8,15,16,23,42])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

108
18.0
4
42
12.315302134607444
151.66666666666666


You can also do the axis based operations row-Wise and Colum-wise

In [10]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.sum(data,axis=1))
print(np.sum(data,axis=0))
print(np.mean(data,axis=0))
print(np.mean(data,axis=0))


[ 6 15 24]
[12 15 18]
[4. 5. 6.]
[4. 5. 6.]
