##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [6]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


Now lets see the 2D indexing aswell

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr[0]

array([1, 2, 3])

In [10]:
arr[2,2]

np.int64(9)

Now we can also do the slicing lets see the **slicing in 1D**

In [11]:
a = np.array([1,2,3,4,5])
a[:3]

array([1, 2, 3])

1D slicing was really easy now lets see the **slicing in 2D**

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(arr)
arr[1:,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [15]:
arr = np.array([5,10,20,30,40])
print(arr>12)

[False False  True  True  True]


In [16]:
print (arr[arr>12])

[20 30 40]


In [17]:
arr>5

array([False,  True,  True,  True,  True])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [19]:
np.arange(1,31).reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [20]:
a.flatten()

array([1, 2, 3, 4, 5])