# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5,]
print(a)

[1, 2, 3, 4, 5]


In [ ]:
import numpy as np
a = [1,2,3,4,5,]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np
a = [1,2,3,4,5,]
arr = np.array([1,2,3,4,5,])
arr.dtype


dtype('int64')

In [ ]:
import numpy as np

arr = np.array(['1',2,3,4,5,])
arr.dtype

dtype('<U21')

In [ ]:
import numpy as np

arr = np.array(['1',2,3,4,5,])
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')

Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([11,11])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones([11,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full([5,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
import numpy as np
a = [1,2,3,4,5,]
arr = np.array(a)
np.random.rand(5,5)

array([[0.58635454, 0.32283377, 0.24456456, 0.68990509, 0.9641515 ],
       [0.47027218, 0.37600704, 0.76137352, 0.51592272, 0.65094688],
       [0.18111453, 0.66820501, 0.67001201, 0.4596993 , 0.44432007],
       [0.08254512, 0.62260605, 0.09993656, 0.23396259, 0.48502915],
       [0.66108969, 0.4844157 , 0.23774206, 0.05681675, 0.64266348]])

In [2]:
import numpy as np
a = [1,2,3,4,5,]
arr = np.array(a)
np.random.randint(5,25,(5,5))


array([[ 9, 15,  5,  5, 11],
       [ 6, 15, 18, 21, 15],
       [13, 18,  7, 12,  9],
       [24, 17, 15, 15, 17],
       [ 9, 19, 15, 10,  5]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution